// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] used by `Firebase.initializeApp()`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWebConfig00000000000',
    appId: '1:1234567890:web:dummy123456',
    messagingSenderId: '1234567890',
    projectId: 'presenza-app',
    authDomain: 'presenza-app.firebaseapp.com',
    databaseURL: 'https://presenza-app-default-rtdb.firebaseio.com',
    storageBucket: 'presenza-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForAndroidConfig0000000',
    appId: '1:1234567890:android:dummy123456',
    messagingSenderId: '1234567890',
    projectId: 'presenza-app',
    databaseURL: 'https://presenza-app-default-rtdb.firebaseio.com',
    storageBucket: 'presenza-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIosConfig00000000000',
    appId: '1:1234567890:ios:dummy123456',
    messagingSenderId: '1234567890',
    projectId: 'presenza-app',
    databaseURL: 'https://presenza-app-default-rtdb.firebaseio.com',
    storageBucket: 'presenza-app.appspot.com',
    iosBundleId: 'com.example.presenza',
  );
}
