// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] used by `Firebase.initializeApp()`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBusbbSBtuR-ozyhOyko7J6Z_j3p1gtNbA',
    appId: '1:735183066067:web:76a5704526e39dceefd526',
    messagingSenderId: '735183066067',
    projectId: 'presenza-9115c',
    authDomain: 'presenza-9115c.firebaseapp.com',
    databaseURL: 'https://presenza-9115c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'presenza-9115c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBusbbSBtuR-ozyhOyko7J6Z_j3p1gtNbA',
    appId: '1:735183066067:android:76a5704526e39dceefd526',
    messagingSenderId: '735183066067',
    projectId: 'presenza-9115c',
    databaseURL: 'https://presenza-9115c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'presenza-9115c.firebasestorage.app',
  );
}
